### ISSUE TITLE
[FEATURE-REQUEST] HP Elite c1030 Chromebook is not listed in Supported devices

### ISSUE THREAD

**Issue by Integral-Tech** [eupnea-linux/eupnea-linux.github.io#18]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

I am frustrated to find HP Elite c1030 Chromebook not listed in supported devices.

**Describe the solution you'd like**

Add the support for HP Elite c1030 Chromebook.

**Additional context**

**Comment by Apacelus** [comment]
Fixed in d9c9b0e7cff829751d10302cb897eec87ab9915b
