### ISSUE TITLE
No pros or cons about crostini listed

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [eupnea-linux/eupnea-linux.github.io#19]
"vs Crostini" is written here:
https://github.com/eupnea-linux/eupnea-linux.github.io/blob/6b413512701edb68478174e981b728a8ae10d155/docs/chromebook/firmware-comparison.md?plain=1#L1
but there are no pros or cons about crostini in the section

**Comment by Apacelus** [comment]
Its a typo

You can make prs for that kinda stuff too (if you want to of course)

**Comment by Apacelus** [comment]
Fixed in commit/27ebce91f54a91362147d43f603264960f00a14e

**Comment by ChocolateLoverRaj** [comment]
I might make a comparison comparing Crostini, Termux, Crouton, Chrx, and Eupnea/Depthboot.

**Comment by Apacelus** [comment]
There is no point in that... The page is comparing firmware
