### ISSUE TITLE
What happens after `install-to-internal`?

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [eupnea-linux/eupnea-linux.github.io#21]
https://github.com/eupnea-linux/eupnea-linux.github.io/blob/951c27e2bf9748b0f5202641cdf32daae5c6035a/docs/depthboot/install-to-internal.md?plain=1#L7-L8

When I read that on the website I was confused. Do you press Ctrl+D next time the computer turns on to launch Linux? It might be very obvious _after_ running the command, but it would be nice to have some info on the web page.

**Comment by Apacelus** [comment]
The script tells you what to do after you run it

**Comment by Apacelus** [comment]
Also, soon there will be a graphical eupnea settings app, which will replace all scripts
